language: python
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install . # install package + test dependencies
script: 
  - pytest # run tests
#https://towardsdatascience.com/extensive-python-testing-on-travis-ci-4c24db9bf961
